import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { extractHtmlDoc } from "@hia-doc/html-doc-extractor";
import { createHtmlDocumentationSourceMap } from "@hia-doc/html-doc-source-map";
import {
  createHtmlAuthoringDocumentationHandoff,
  createHtmlAuthoringSourceCommentProjectionRequest
} from "@hia-doc/htmdoc-runner";

const workspaceRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fixturePath = "fixtures/html-authoring-source-comment-integration/fixture.html";

test("HTML-authoring fixture creates an exact W-P96 request with explicit ordinary-map identity", async () => {
  const { extraction, docSourceMap } = await createFixtureArtifacts();
  const symbolId = "html:component:statusbadge";
  const request = createHtmlAuthoringSourceCommentProjectionRequest({
    contentPolicy: "explicit-projected-text",
    documentId: "htmdoc:fixture:status-badge",
    docSourceMap,
    extraction,
    fallbackLocales: ["en"],
    projectionId: "projection:status-badge:description",
    requestedLocale: "zh-CN",
    symbolId
  });
  const mapEntry = docSourceMap.entries.find((entry) => entry.symbolId === symbolId);

  assert.equal(request.contract, "documentation-source-comment-projection");
  assert.equal(request.contractVersion, "0.1.0-draft");
  assert.equal(request.source.docSourceMapEntryId, mapEntry.id);
  assert.equal(request.source.sourceId, mapEntry.sourceRefs[0].sourceId);
  assert.equal(request.comments[0].localizedText.en, "Shows the current status.");
  assert.equal(request.comments[0].localizedText["zh-CN"], "显示当前状态。");
  assert.deepEqual(request.comments[0].range.start, { line: 1, column: 0 });
  assert.deepEqual(request.comments[0].range.end, { line: 6, column: 3 });
  assert.equal(Object.hasOwn(request, "sourceBody"), false);
  assert.equal(JSON.stringify(request).includes("<!--"), false);

  // <lang><zh-CN>handoff entry 与 doc-map entry 分开声明，跨 owner verifier 后续只验证 explicit binding，不推导二者同形。</zh-CN><en>The handoff entry and doc-map entry are declared separately; the cross-owner verifier later checks an explicit binding without inferring equal string forms.</en></lang>
  const handoff = createHtmlAuthoringDocumentationHandoff(createHandoffRequest(mapEntry.id));
  assert.equal(handoff.status, "accepted");
  assert.deepEqual(handoff.output.stableEntryIds, [mapEntry.id]);
});

test("HTML-authoring projection request adapter refuses non-none ordinary maps", async () => {
  const { extraction, docSourceMap } = await createFixtureArtifacts();
  const unsafeMap = structuredClone(docSourceMap);
  unsafeMap.privacy.sourcesContentPolicy = "embed";

  assert.throws(() => createHtmlAuthoringSourceCommentProjectionRequest({
    contentPolicy: "none",
    documentId: "htmdoc:fixture:status-badge",
    docSourceMap: unsafeMap,
    extraction,
    fallbackLocales: [],
    projectionId: "projection:status-badge:description",
    requestedLocale: "en",
    symbolId: "html:component:statusbadge"
  }), /none-only ordinary doc-source-map/);
});

/**
 * Materialize the HIA-owned bilingual fixture entirely inside the HTMDoc owner process.
 *
 * 中文：完全在 HTMDoc owner process 内 materialize HIA-owned bilingual fixture。
 * English: Materialize the HIA-owned bilingual fixture entirely inside the HTMDoc owner process.
 *
 * @returns {Promise<{extraction:Record<string,unknown>,docSourceMap:Record<string,unknown>}>} <lang><zh-CN>already-materialized extraction 与 none-only map。</zh-CN><en>Already-materialized extraction and none-only map.</en></lang>
 * @lang zh-CN helper 只读取仓内固定 fixture；不访问目标项目、host 或 network。
 */
async function createFixtureArtifacts() {
  const source = await readFile(path.join(workspaceRoot, fixturePath), "utf8");
  const extraction = extractHtmlDoc(source, { path: fixturePath, fragment: true });
  const docSourceMap = createHtmlDocumentationSourceMap({
    extraction,
    extractionPath: "artifacts/fixture.htmdoc.json",
    hiaDocumentPath: "artifacts/fixture.hia.json",
    sourcesContentPolicy: "none"
  });
  return { extraction, docSourceMap };
}

/**
 * Build an exact W-P80 metadata handoff request for the real map entry.
 *
 * 中文：为真实 map entry 构造 exact W-P80 metadata handoff request。
 * English: Build an exact W-P80 metadata handoff request for the real map entry.
 *
 * @param {string} entryId <lang><zh-CN>doc-source-map 已生成的 stable entry id。</zh-CN><en>Stable entry ID generated by the doc-source-map.</en></lang>
 * @returns {Record<string,unknown>} <lang><zh-CN>全部 privacy/permission 关闭的 handoff request。</zh-CN><en>Handoff request with every privacy/permission capability disabled.</en></lang>
 */
function createHandoffRequest(entryId) {
  return {
    contract: "html-authoring-documentation-handoff-request",
    contractVersion: "0.1.0-draft",
    output: { id: "htmdoc-output:status-badge", stableEntryIds: [entryId], locale: "en" },
    producer: { id: "htmdoc", version: "0.0.0", status: "success" },
    conformance: {
      contract: "htmdoc-output-conformance",
      contractVersion: "0.1.0-draft",
      conformant: true,
      violations: []
    },
    docSourceMap: {
      contract: "doc-source-map",
      contractVersion: "0.1.0-draft",
      linkage: "explicit-reference-only",
      carriesHandoffModel: false,
      sourcesContentPolicy: "none"
    },
    privacy: {
      sourceBodySerialized: false,
      mapBodySerialized: false,
      sidecarBodySerialized: false,
      absolutePathSerialized: false,
      rawLocatorSerialized: false,
      credentialSerialized: false,
      workingStateSerialized: false
    },
    permissions: {
      targetRepositoryRead: false,
      targetRepositoryWrite: false,
      targetCommandExecuted: false,
      targetRuntimeOpened: false,
      tauriIpcIntegration: false,
      obsidianVaultIntegration: false,
      sourceReaderImplemented: false,
      fetchEnabled: false,
      networkAccessed: false,
      packagePublished: false,
      targetAdoptionClaimed: false
    }
  };
}
